/**
 * Placeholder embeddings service for open-source local vector storage.
 *
 * This file can be expanded to use:
 * - ChromaDB
 * - FAISS
 * - local embeddings generated by Ollama / local transformer models
 *
 * The current implementation stores documents in memory and exposes basic APIs.
 */

interface EmbeddingRecord {
  id: string;
  text: string;
  vector: number[];
}

const localEmbeddings: EmbeddingRecord[] = [];

export const storeDocumentEmbedding = async (id: string, text: string, vector: number[]) => {
  localEmbeddings.push({ id, text, vector });
  return { id, stored: true };
};

export const searchEmbeddings = async (queryVector: number[], limit = 5) => {
  const distance = (a: number[], b: number[]) =>
    Math.sqrt(a.reduce((sum, value, index) => sum + Math.pow(value - (b[index] || 0), 2), 0));

  return localEmbeddings
    .map((record) => ({ record, score: distance(queryVector, record.vector) }))
    .sort((a, b) => a.score - b.score)
    .slice(0, limit)
    .map(({ record }) => ({ id: record.id, text: record.text }));
};
